# Generated by Django 5.0.3 on 2024-03-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_status_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_token_exchange',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
