# Generated by Django 5.0.3 on 2024-03-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='outer_price',
            new_name='out_price',
        ),
    ]
