# Generated by Django 5.0.3 on 2024-03-26 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_category_slug_product_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proporties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=455)),
                ('value', models.CharField(max_length=455)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proporties', to='product.product')),
            ],
        ),
    ]
