# Generated by Django 5.0.4 on 2024-05-05 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_slug',
        ),
        migrations.AlterField(
            model_name='proporties',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='product.product'),
        ),
    ]
