# Generated by Django 5.0.3 on 2024-04-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_seller_first_name_seller_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='id_number_of_passport',
            field=models.CharField(default='AD0000000', max_length=9),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
